---
defaults: &defaults
  environment:
    GOOGLE_PROJECT_ID: planet-4-151612
    DOCKER_BUILDKIT: 0
  docker:
    - image: greenpeaceinternational/circleci-base:latest
  working_directory: /home/circleci/app

version: 2

jobs:
  build-test-push:
    <<: *defaults
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: make lint
      - run: make clean
      - run: make pull
      - run: make build
      - run: make test
      - run: docker-login.sh
      - run: |
          mkdir -p /tmp/workspace/var
          echo "${CIRCLE_BUILD_NUM}" > /tmp/workspace/var/circle-build-num
      - run: make -j2 push
      - run:
          name: Notify failure
          when: on_fail
          command: TYPE="Build-push greenpeaceinternational/p4-nro-recharge" notify-job-failure.sh

  promote:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Release
          command: |
            new_version=$(git-new-version.sh)
            echo "Promoting to ${new_version}"
            release-start.sh $new_version
            release-finish.sh $new_version

  daily:
    docker:
      - image: greenpeaceinternational/p4-nro-recharge:latest
    environment:
      RECHARGE_PERIOD: day
    steps:
      - run: go.sh

  monthly:
    docker:
      - image: greenpeaceinternational/p4-nro-recharge:latest
    environment:
      RECHARGE_PERIOD: month
    steps:
      - run: go.sh

  yearly:
    docker:
      - image: greenpeaceinternational/p4-nro-recharge:latest
    environment:
      RECHARGE_PERIOD: year
    steps:
      - run: go.sh

  id:
    docker:
      - image: greenpeaceinternational/p4-nro-recharge:latest
    environment:
      FORCE_RECREATE_ID: true
    steps:
      - run: rebuild-id.sh

workflows:
  version: 2
  branch:
    jobs:
      - build-test-push:
          context: org-global
          filters:
            branches:
              ignore: master
      - promote:
          context: org-global
          requires:
            - build-test-push
          filters:
            branches:
              only: develop

  tag:
    jobs:
      - build-test-push:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

  daily:
    jobs:
      - daily
    triggers:
      - schedule:
          cron: "5 2 * * *"
          filters:
            branches:
              only:
                - master
  monthly:
    jobs:
      - monthly
    triggers:
      - schedule:
          cron: "11 3 2 * *"
          filters:
            branches:
              only:
                - master

  yearly:
    jobs:
      - yearly
    triggers:
      - schedule:
          cron: "33 3 2 1 *"
          filters:
            branches:
              only:
                - master

  recreate-id:
    jobs:
      - id:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /id.*/
