FROM ${PARENT_IMAGE}

# hadolint ignore=DL3018
RUN apk add --no-cache \
  bash \
  coreutils \
  curl \
  jq

RUN curl -L "https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl" -o /usr/local/bin/kubectl && \
  chmod 755 /usr/local/bin/kubectl

WORKDIR /app

ENTRYPOINT ["entrypoint.sh"]

CMD ["go.sh"]

ENV \
  BATCH_UPLOAD="true" \
  BIGQUERYRC="/app/.bigqueryrc" \
  NEWRELIC_APP_ID="" \
  NEWRELIC_APP_NAME="" \
  NEWRELIC_REST_API_KEY="" \
  PATH="/app/bin:${PATH}" \
  RECHARGE_BQ_DATASET="recharge" \
  RECHARGE_BUCKET_LOCATION="us" \
  RECHARGE_BUCKET_NAME="${RECHARGE_BUCKET_NAME}" \
  RECHARGE_BUCKET_PATH="" \
  RECHARGE_OUTPUT_FILE="/tmp/sla.json" \
  RECHARGE_PERIOD_DAY="" \
  RECHARGE_PERIOD_MONTH="" \
  RECHARGE_PERIOD_YEAR="" \
  RECHARGE_PERIOD="month" \
  RECHARGE_PROJECT_ID="${RECHARGE_PROJECT_ID}" \
  RECHARGE_SERVICE_KEY="" \
  RECHARGE_SERVICE_KEY_FILE="${RECHARGE_SERVICE_KEY_FILE}" \
  SCHEMA_VERSION="5" \
  USAGE_BUCKET_NAME="p4-gcs-usage"

COPY . /app
